package codingcheck1;

public class ExceptionScenario2 {
	int modifiedInt() {
	    int returnVal = 10;
	    try {
	      String[] students = {"harry", "paul"};
	      System.out.println(students[5]);
	    } catch (Exception e) {
	      System.out.println("About to return: " + returnVal);
	      return returnVal;
	    } finally {
	      returnVal += 10;  
	      System.out.println("Return value is now: " + returnVal);
	    }
	    return returnVal;
	  }
	 public static void main(String[] args) {
		    ExceptionScenario2 var = new ExceptionScenario2();
		    System.out.println("In main: " + var.modifiedInt()); // 10
		   
		  }
}
